#!/usr/bin/env ansible-playbook
---
- name: create infrastructure
  hosts: localhost
  gather_facts: no

  tasks:
    - name: apply terraform code
      terraform:
        project_path: ./terraform
        state: present
        force_init: yes
      register: terraform

    - name: add vault_a to inventory
      add_host:
        name: "{{ item }}"
        groups:
          - vault_a
      loop: "{{ terraform.outputs.vault_a.value }}"

    - name: add vault_b to inventory
      add_host:
        name: "{{ item }}"
        groups:
          - vault_b
      loop: "{{ terraform.outputs.vault_b.value }}"

    - name: add loadbalancer_a to inventory
      add_host:
        name: "{{ item }}"
        groups:
          - loadbalancer_a
      loop: "{{ terraform.outputs.loadbalancer_a.value }}"

    - name: add loadbalancer_b to inventory
      add_host:
        name: "{{ item }}"
        groups:
          - loadbalancer_b
      loop: "{{ terraform.outputs.loadbalancer_b.value }}"

    - name: add loadbalancer to inventory
      add_host:
        name: "{{ item }}"
        groups:
          - loadbalancer
      loop: "{{ terraform.outputs.loadbalancer.value }}"

    - name: wait a moment to allow dns updates
      pause:
        seconds: 15

- name: install shared components
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.core_dependencies
    - role: robertdebock.common
    - role: robertdebock.digitalocean_agent

- name: install vault components
  hosts: vault_a:vault_b
  become: yes
  gather_facts: yes

  roles:
    - role: robertdebock.users
    - role: robertdebock.hashicorp
      hashicorp_products:
        - name: vault
          type: "{{ vault_type }}"
          version: "{{ vault_version }}"
    - role: robertdebock.service
    - role: robertdebock.environment

- name: install vault-a components
  hosts: vault_a
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.vault
      vault_show_unseal_information: yes

  post_tasks:
    - name: save a unseal keys and root token in group_vars
      template:
        src: vault.yml.j2
        dest: group_vars/vault_a/vault.yml
      when:
        - vault_init_output is defined
        - vault_init_output.unseal_keys_b64 is defined
        - vault_init_output is defined
        - vault_init_output.root_token is defined
      delegate_to: localhost
      become: no
      run_once: yes

- name: install vault-b components
  hosts: vault_b
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.vault
      vault_show_unseal_information: yes

  post_tasks:
    - name: save a unseal keys and root token in group_vars
      template:
        src: vault.yml.j2
        dest: group_vars/vault_b/vault.yml
      when:
        - vault_init_output is defined
        - vault_init_output.unseal_keys_b64 is defined
        - vault_init_output is defined
        - vault_init_output.root_token is defined
      delegate_to: localhost
      become: no
      run_once: yes

- name: install loadbalancer components
  hosts: loadbalancer_a:loadbalancer_b:loadbalancer
  become: yes
  gather_facts: yes

  roles:
    - role: robertdebock.haproxy
    - role: robertdebock.keepalived

- name: show loadbalancer endpoints
  debug:
    msg:
      - "loadbalancer-a-0: http://loadbalancer-a-0.meinit.nl:1936/stats"
      - "loadbalancer-a-1: http://loadbalancer-a-1.meinit.nl:1936/stats"
      - "loadbalancer-b-0: http://loadbalancer-b-0.meinit.nl:1936/stats"
      - "loadbalancer-b-1: http://loadbalancer-b-1.meinit.nl:1936/stats"
      - "loadbalancer-0: http://loadbalancer-0.meinit.nl:1936/stats"
      - "loadbalancer-0: http://loadbalancer-1.meinit.nl:1936/stats"
