#!/usr/bin/env ansible-playbook
---

- name: create infrastructure
  hosts: localhost
  gather_facts: no

  tasks:
    - name: include 0_terraform
      include: 0_terraform.yml

  handlers:
    - name: pause
      pause:
        seconds: 15

- name: install shared components
  hosts: all
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.bootstrap
    - role: robertdebock.core_dependencies
    - role: robertdebock.common
    - role: robertdebock.digitalocean_agent

- name: install vault components
  hosts: vault
  become: yes
  gather_facts: yes

  roles:
    - role: robertdebock.users
    - role: robertdebock.hashicorp
    - role: robertdebock.service
    - role: robertdebock.environment
    - role: robertdebock.logrotate

- name: install vault-a components
  hosts: vault_a
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.vault
      vault_show_unseal_information: yes

  post_tasks:
    - name: save a unseal keys and root token in group_vars
      template:
        src: vault.yml.j2
        dest: group_vars/vault_a/vault.yml
      when:
        - vault_init_output is defined
        - vault_init_output.unseal_keys_b64 is defined
        - vault_init_output is defined
        - vault_init_output.root_token is defined
      delegate_to: localhost
      become: no
      run_once: yes

- name: install vault-b components
  hosts: vault_b
  become: yes
  gather_facts: no

  roles:
    - role: robertdebock.vault
      vault_show_unseal_information: yes

  post_tasks:
    - name: save a unseal keys and root token in group_vars
      template:
        src: vault.yml.j2
        dest: group_vars/vault_b/vault.yml
      when:
        - vault_init_output is defined
        - vault_init_output.unseal_keys_b64 is defined
        - vault_init_output is defined
        - vault_init_output.root_token is defined
      delegate_to: localhost
      become: no
      run_once: yes

- name: install loadbalancer components
  hosts: loadbalancers
  become: yes
  gather_facts: yes

  roles:
    - role: robertdebock.haproxy
    - role: robertdebock.keepalived
