#!/usr/bin/env ansible-playbook
---
  
- name: create infrastructure
  hosts: localhost
  gather_facts: no

  tasks:
    - name: include 0_terraform
      include: 0_terraform.yml

- name: backup vault
  hosts: vault_a:vault_b
  become: yes
  gather_facts: yes

  roles:
    - role: robertdebock.vault
      vault_make_backup: yes
