#!/usr/bin/env ansible-playbook
---
- name: create machines
  hosts: localhost
  gather_facts: no

  tasks:
    - name: apply terraform code
      terraform:
        project_path: ./terraform
        state: present
        force_init: yes
      register: terraform

    - name: add terraform hosts a to inventory
      add_host:
        name: "{{ item }}"
        groups:
          - a
      loop: "{{ terraform.outputs.a.value }}"

    - name: add terraform hosts b to inventory
      add_host:
        name: "{{ item }}"
        groups:
          - b
      loop: "{{ terraform.outputs.b.value }}"

    - name: wait a moment to allow dns updates
      pause:
        seconds: 15

- name: backup vault
  hosts: all
  become: yes
  gather_facts: yes

  roles:
    - role: robertdebock.vault
      vault_make_backup: yes
