#!/usr/bin/env ansible-playbook
---
- name: create machines
  hosts: localhost
  gather_facts: no

  tasks:
    - name: apply terraform code
      terraform:
        project_path: ./terraform
        state: present
        force_init: yes
      register: terraform

    - name: add vault_a to inventory
      add_host:
        name: "{{ item }}"
        groups:
          - vault_a
      loop: "{{ terraform.outputs.vault_a.value }}"

    - name: add vault_b to inventory
      add_host:
        name: "{{ item }}"
        groups:
          - vault_b
      loop: "{{ terraform.outputs.vault_b.value }}"

    - name: add loadbalancer_a to inventory
      add_host:
        name: "{{ item }}"
        groups:
          - loadbalancer_a
      loop: "{{ terraform.outputs.loadbalancer_a.value }}"

    - name: add loadbalancer_b to inventory
      add_host:
        name: "{{ item }}"
        groups:
          - loadbalancer_b
      loop: "{{ terraform.outputs.loadbalancer_b.value }}"

    - name: add loadbalancer to inventory
      add_host:
        name: "{{ item }}"
        groups:
          - loadbalancer
      loop: "{{ terraform.outputs.loadbalancer.value }}"

    - name: wait a moment to allow dns updates
      pause:
        seconds: 15

- name: backup vault
  hosts: vault_a:vault_b
  become: yes
  gather_facts: yes

  roles:
    - role: robertdebock.vault
      vault_make_backup: yes
