#!/usr/bin/env ansible-playbook
---

- name: create infrastructure
  hosts: localhost
  gather_facts: no

  tasks:
    - name: include 0_terraform
      include: 0_terraform.yml

  handlers:
    - name: pause
      pause:
        seconds: 15

- name: upgrade vault to 1.8.1
  hosts: vault_b:vault_a
  become: yes
  gather_facts: yes
  serial: 1

  tasks:
    - name: stop vault
      service:
        name: vault
        state: stopped

    - name: install vault 1.8.1
      include_role:
        name: robertdebock.hashicorp
      vars:
        hashicorp_products:
          - name: vault
            version: 1.8.1
            type: "{{ vault_type }}"

    - name: start vault
      service:
        name: vault
        state: started

    - name: unseal vault
      command: vault operator unseal {{ item }}
      environment:
        VAULT_ADDR: "{{ vault_api_addr }}"
      loop: "{{ vault_init_output.unseal_keys_b64 | default(vault_unseal_keys) }}"
      loop_control:
        label: "hidden"
      no_log: yes
      register: vault_unseal_vault
      until:
        - vault_unseal_vault is succeeded
      retries: 3
