#!/usr/bin/env ansible-playbook
---
- name: create machines
  hosts: localhost
  gather_facts: no

  tasks:
    - name: apply terraform code
      terraform:
        project_path: ./terraform
        state: present
        force_init: yes
      register: terraform

    - name: add vault_a to inventory
      add_host:
        name: "{{ item }}"
        groups:
          - vault_a
      loop: "{{ terraform.outputs.vault_a.value }}"

    - name: add vault_b to inventory
      add_host:
        name: "{{ item }}"
        groups:
          - vault_b
      loop: "{{ terraform.outputs.vault_b.value }}"

    - name: add loadbalancer_a to inventory
      add_host:
        name: "{{ item }}"
        groups:
          - loadbalancer_a
      loop: "{{ terraform.outputs.loadbalancer_a.value }}"

    - name: add loadbalancer_b to inventory
      add_host:
        name: "{{ item }}"
        groups:
          - loadbalancer_b
      loop: "{{ terraform.outputs.loadbalancer_b.value }}"

    - name: add loadbalancer to inventory
      add_host:
        name: "{{ item }}"
        groups:
          - loadbalancer
      loop: "{{ terraform.outputs.loadbalancer.value }}"

    - name: wait a moment to allow dns updates
      pause:
        seconds: 15

- name: upgrade vault to 1.8.1
  # Use the reverse order, leader last.
  hosts: vault_a:vault_b
  become: yes
  gather_facts: yes
  # Run on 2 hosts at a time, 1 from "a", 1 from "b".
  serial: 1

  tasks:
    - name: stop vault
      service:
        name: vault
        state: stopped

    - name: install vault 1.8.1
      include_role:
        name: robertdebock.hashicorp
      vars:
        hashicorp_products:
          - name: vault
            version: 1.8.1
            type: "{{ vault_type }}"

    - name: start vault
      service:
        name: vault
        state: started

    - name: unseal vault
      command: vault operator unseal {{ item }}
      environment:
        VAULT_ADDR: "{{ vault_api_addr }}"
      loop: "{{ vault_init_output.unseal_keys_b64 | default(vault_unseal_keys) }}"
      loop_control:
        label: "hidden"
      no_log: yes
      register: vault_unseal_vault
      until:
        - vault_unseal_vault is succeeded
      retries: 3
