#!/usr/bin/env ansible-playbook
---

- name: upgrade vault to 1.6.0
  # Use the reverse order, leader last.
  hosts: vault-*-3:vault-*-2:vault-*-1
  become: yes
  gather_facts: yes
  # Run on 2 hosts at a time, 1 from "a", 1 from "b".
  serial: 2

  tasks:
    - name: stop vault
      service:
        name: vault
        state: stopped

    - name: install vault 1.6.0
      include_role:
        name: robertdebock.hashicorp
      vars:
        hashicorp_products:
          - name: vault
            version: 1.6.0
            type: ent

    - name: start vault
      service:
        name: vault
        state: started

    - name: unseal vault
      command: vault operator unseal {{ item }}
      environment:
        VAULT_ADDR: "{{ vault_api_addr }}"
      loop: "{{ vault_init_output.unseal_keys_b64 | default(vault_unseal_keys) }}"
      loop_control:
        label: "hidden"
      no_log: yes
      register: vault_unseal_vault
      until:
        - vault_unseal_vault is succeeded
      retries: 3
