#!/usr/bin/env ansible-playbook
---
- name: create machines
  hosts: localhost
  gather_facts: no

  tasks:
    - name: apply terraform code
      terraform:
        project_path: ./terraform
        state: present
        force_init: yes
      register: terraform

    - name: add terraform hosts a to inventory
      add_host:
        name: "{{ item }}"
        groups:
          - a
      loop: "{{ terraform.outputs.a.value }}"

    - name: add terraform hosts b to inventory
      add_host:
        name: "{{ item }}"
        groups:
          - b
      loop: "{{ terraform.outputs.b.value }}"

    - name: wait a moment to allow dns updates
      pause:
        seconds: 15

- name: setup vault primary cluster
  hosts: vault-a-1.meinit.nl
  become: yes
  gather_facts: yes

  tasks:
    - name: make cluster primary
      block:
        - name: dr enable primary
          command: vault write -f sys/replication/dr/primary/enable
          environment:
            VAULT_ADDR: "{{ vault_api_addr }}"
            VAULT_TOKEN: "{{ vault_root_token }}"

    - name: generate token for secondary cluster
      command: vault write sys/replication/dr/primary/secondary-token id="secondary" -format=yaml
      register: vault_secondary_token_raw
      environment:
        VAULT_ADDR: "{{ vault_api_addr }}"
        VAULT_TOKEN: "{{ vault_root_token }}"

    - name: save token for secondary cluster
      set_fact:
        vault_secondary_token: "{{ vault_secondary_token_raw.stdout | from_yaml }}"

- name: setup vault secondary cluster
  hosts: vault-b-1.meinit.nl
  become: yes
  gather_facts: yes

  tasks:
    - name: join primary as secondary
      command: vault write sys/replication/dr/secondary/enable token="{{ hostvars['vault-a-1']['vault_secondary_token']['wrap_info']['token'] }}"
      environment:
        VAULT_ADDR: "{{ vault_api_addr }}"
        VAULT_TOKEN: "{{ vault_root_token }}"
