#!/usr/bin/env ansible-playbook
---

- name: generate failover token
  hosts: vault-a-1
  become: yes
  gather_facts: yes

  tasks:
    - name: place vault policy dr-secondary-promotion
      copy:
        dest: /root/dr-secondary-promotion.policy
        content: |
          path "sys/replication/dr/secondary/promote" {
            capabilities = [ "update" ]
          }

    - name: write vault policy dr-secondary-promotion
      command: vault policy write dr-secondary-promotion /root/dr-secondary-promotion.policy
      environment:
        VAULT_ADDR: "{{ vault_api_addr }}"
        VAULT_TOKEN: "{{ vault_root_token }}"

    - name: create vault role failover-handler
      command: vault write auth/token/roles/failover-handler allowed_policies=dr-secondary-promotion orphan=true renewable=false token_type=batch
      environment:
        VAULT_ADDR: "{{ vault_api_addr }}"
        VAULT_TOKEN: "{{ vault_root_token }}"

    - name: create token for failover-handler
      command: vault token create -role=failover-handler -ttl=8h -format=yaml
      register: vault_create_failover_token_raw
      environment:
        VAULT_ADDR: "{{ vault_api_addr }}"
        VAULT_TOKEN: "{{ vault_root_token }}"

    - name: save vault_create_failover_token
      set_fact:
        vault_create_failover_token: "{{ vault_create_failover_token_raw.stdout | from_yaml }}"

    - name: show failover-handler token
      debug:
        msg: "{{ vault_create_failover_token.auth.client_token }}"
