#!/usr/bin/env ansible-playbook
---

- name: create infrastructure
  hosts: localhost
  gather_facts: no

  tasks:
    - name: include 0_terraform
      include: 0_terraform.yml

  handlers:
    - name: pause
      pause:
        seconds: 15

- name: configure audit log
  hosts: vault-a-0.meinit.nl
  become: no
  gather_facts: yes

  tasks:
    - name: check
      command:
        cmd: vault audit enable file file_path={{ vault_audit_path }}
      environment:
        VAULT_ADDR: "{{ vault_api_addr }}"
        VAULT_TOKEN: "{{ vault_root_token }}"
