#!/usr/bin/env ansible-playbook
---
- name: create machines
  hosts: localhost
  gather_facts: no

  tasks:
    - name: apply terraform code
      terraform:
        project_path: ./terraform
        state: present
        force_init: yes
      register: terraform

    - name: add vault_a to inventory
      add_host:
        name: "{{ item }}"
        groups:
          - vault_a
      loop: "{{ terraform.outputs.vault_a.value }}"

    - name: add vault_b to inventory
      add_host:
        name: "{{ item }}"
        groups:
          - vault_b
      loop: "{{ terraform.outputs.vault_b.value }}"

    - name: add loadbalancer_a to inventory
      add_host:
        name: "{{ item }}"
        groups:
          - loadbalancer_a
      loop: "{{ terraform.outputs.loadbalancer_a.value }}"

    - name: add loadbalancer_b to inventory
      add_host:
        name: "{{ item }}"
        groups:
          - loadbalancer_b
      loop: "{{ terraform.outputs.loadbalancer_b.value }}"

    - name: add loadbalancer to inventory
      add_host:
        name: "{{ item }}"
        groups:
          - loadbalancer
      loop: "{{ terraform.outputs.loadbalancer.value }}"

    - name: wait a moment to allow dns updates
      pause:
        seconds: 15
        
- name: restart and unseal vault
  hosts: all
  become: yes
  gather_facts: yes
  serial: 1

  tasks:
    - name: restart vault
      service:
        name: vault
        state: restarted

    - name: unseal vault
      command: vault operator unseal {{ item }}
      register: vault_unseal_vault
      until: vault_unseal_vault is succeeded
      retries: 3
      environment:
        VAULT_ADDR: "{{ vault_api_addr }}"
      loop: "{{ vault_init_output.unseal_keys_b64 | default(vault_unseal_keys) }}"
      loop_control:
        label: "hidden"
      no_log: yes

- name: show ha status
  hosts: vault-*-1.meinit.nl
  become: yes
  gather_facts: no

  tasks:
    - name: get peers list
      command: vault operator raft list-peers
      register: vault_list_peers
      environment:
        VAULT_ADDR: "{{ vault_api_addr }}"
        VAULT_TOKEN: "{{ vault_root_token }}"

    - name: show peers
      debug:
        msg: "{{ vault_list_peers.stdout }}"
