---

haproxy_frontends:
  - name: vault_a
    address: "*"
    port: 8200
    default_backend: backend

haproxy_backends:
  - name: backend
    httpcheck: yes
    httpcheck_method: GET /v1/sys/health
    servers: "{{ groups['vault_a'] }}"
    port: 8200
    options:
      - check
