---

vault_version: 1.8.0
vault_type: ent

vault_listeners:
  - name: tcp
    address: "{{ ansible_default_ipv4.address }}:8200"
    cluster_address: "{{ ansible_default_ipv4.address }}:8201"
    tls_disable: "true"
vault_api_addr: "http://{{ ansible_default_ipv4.address }}:8200"
vault_cluster_addr: "https://{{ ansible_default_ipv4.address }}:8201"

vault_license: "02MV4UU43BK5HGYYTOJZWFQMTMNNEWU33JJZVEU2CPK5GTGWTNKV2FSV2KNNHUGMBTLJDUSM2MKRIXSTJSJV2E2MSWNRHGUWTIJYZFM2S2IRHGWSLJO5UVSM2WPJSEOOLULJMEUZTBK5IWST3JJJVE26SBGFMWUSTJLJBTC3C2NJVTETCUKF4E43KJORHVORJTJV4TA6KZKRVXUWSEMRWVSV2JPFGTEVLJJRBUU4DCNZHDAWKXPBZVSWCSOBRDENLGMFLVC2KPNFEXCSLJO5UWCWCOPJSFOVTGMRDWY5C2KNETMSLKJF3U22SFORGUIZ3UJVKFEVKNIRVTMTSEKE3E22SROVGUIVL2JVCGGNCPIRTTKV3JJFZUS3SOGBMVQSRQLAZVE4DCK5KWST3JJF4U2RCJPBGFIQJUJRKEKMCWIRATKT3KKEYE62SJPJLWSSLTJFWVMNDDI5WHSWKYKJYGEMRVMZSEO3DULJJUSNSJNJEXOTLKIV2E2RDLORGVITSVJVCGWNSOIRITMTLKJZQUS2LXNFSEOVTZMJLWY5KZLBJHAYRSGVTGIR3MORNFGSJWJFVES52NNJCXITKENN2E2VCSKVGUI2ZWJZCFCNSNNJHGCSLJO5UWGSCKOZNEQVTKMRBUSNSJNZNGQZCXPAYES2LXNFNG26DILIZU22KPNZZWSYSXHFVWIV3YNRRXSSJWK54UU5DEK54DAYKTGFVVS6JRPJMTERTTLJJUS42JNVSHMZDNKZ4WE3KGOVMTEVLUMNDTS43BK5HDKSLJO5UVSV2SGJMVONLKLJLVC5C2I5DDAWKTGF3WG3JZGBNFOTRQMFLTS5KJNQYTSZSRHU6S4YZWOBCHI5SSGV3TON3HJVIXU3BSONKECVTUJR2XU6D2NZRTE2DFINWG6ZSEKYVTQZLFJZKG2ZLSMN3XUSCYIJZUMZKYGRYXQSCWO5GHS5CONRFWC3KJJFXGO23PJJRHA3JTKFJEI4BRMRAWWY3BGRSFMMBTGM4FA53NKZWGC5SKKA2HASTYJFETSRBWKVDEYVLBKZIGU22XJJ2GGRBWOBQWYNTPJ5TEO3SLGJ5FAS2KKJWUOSCWGNSVU53RIZSSW3ZXNMXXGK2BKRHGQUC2M5JS6S2WLFTS6SZLNRDVA52MG5VEE6CJG5DU6YLLGZKWC2LBJBXWK2ZQKJKG6NZSIRIT2PI"
