---

haproxy_frontends:
  - name: vault
    address: "*"
    port: 8200
    default_backend: backend

haproxy_backends:
  - name: backend
    httpcheck: yes
    httpcheck_method: GET /v1/sys/health
    servers: "{{ groups['loadbalancer_a'] + groups['loadbalancer_b'] }}"
    port: 8200
    options:
      - check
